### ISSUE TITLE
Add, Remove and Find Command Entered as Arguments When Not Followed By Movie

### ISSUE THREAD

**Issue by blbi0875** [Dpasi314/Pasionek_CSCI2270_FinalProject#5]
To begin very impressive code. Great job. In regards to the issue, if I type "add", "remove",or "find" into the terminal without following them with movie titles the methods still run with the names "add", "remove",and "find" serving as the arguments to their respective functions.

To explain, if I simply type add your program prints 

--- Movie List ---
You added the movie: add
URL: http://www.rottentomatoes.com/m/add

and in fact "add" is added to the list of movies that is printed when I hit print.
Similar things happen if I type "remove" or "find"; however, after typing remove I am informed that the title does not exist in my movie list, which is correct.

**Comment by dpasionek** [comment]
Fixed since pull request https://github.com/Dpasi314/Pasionek_CSCI2270_FinalProject/pull/6
Thanks!
